### ISSUE TITLE
can't activate activesupport (= 3.0.0) for [], already activated activesupport-3.0.5 for [] (Gem::LoadError)

### ISSUE THREAD

**Issue by nhocki** [josevalim/enginex#19]
I've just installed enginex and when I try to run it I get the following error.

```
/Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:268:in `activate': can't activate activesupport (= 3.0.0) for [], already activated activesupport-3.0.5 for [] (Gem::LoadError)
from /Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:50:in `block in require'
from /Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in `each'
from /Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in `require'
from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/enginex-0.8.1/lib/enginex.rb:2:in `<top (required)>'
from /Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
from /Users/tesla/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/enginex-0.8.1/bin/enginex:4:in `<top (required)>'
from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/bin/enginex:19:in `load'
from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/bin/enginex:19:in `<main>'
```

Any help is really appreciated. I can't wait to start following the book...

**Comment by josevalim** [comment]
This is weird as Enginex has no direct dependency on ActiveSupport. Maybe you could start a new gemset in RVM from scratch, install only enginex in it and see if it works?

**Comment by nhocki** [comment]
It worked with the new gemset, thanks :-)

I still don't understand why it tries to activate the "lowest" Active Support though.

Thanks again! :-)

**Comment by josevalim** [comment]
I don't understand also. Go figure... :D

**Comment by ricn** [comment]
I just had the same problem. I had Rails 3.0.0, 3.0.3 and 3.0.5 installed. I removed all but 3.0.5 and then enginex started to work :) Time to do chapter 1 now :)

**Comment by tute** [comment]
I also had to cleanup old rails releases to make it work.

```
gem cleanup actionmailer actionpack activemodel activerecord activeresource activesupport rails railties
```

Weird!
