### ISSUE TITLE
can't activate activesupport-3.0.7, already activated activesupport-3.0.9.rc3

### ISSUE THREAD

**Issue by murdoch** [josevalim/enginex#21]
Following the code in your book, when I run:

enginex pdf_renderer

I get this:

```
/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1600:in `raise_if_conflicts': can't activate activesupport-3.0.7, already activated activesupport-3.0.9.rc3 (Gem::LoadError)
from /home/stephen/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:737:in `activate'
```

I have removed rails-3.0.9.rc3 from my system and problem is gone.

**Comment by murdoch** [comment]
PS - I will just revert to rails-3.0.3 if I get any more problems like this
