### ISSUE TITLE
enginex doesn't work with rails 3.0.10

### ISSUE THREAD

**Issue by ghost** [josevalim/enginex#32]
I use command "enginex pdf_renderer", but failed, error info as follow

/home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1603:in `raise_if_conflicts': can't activate activesupport-3.0.0, already activated activesupport-3.0.10 (Gem::LoadError)
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:738:in`activate'
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:51:in `block in require'
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:50:in`each'
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:50:in `require'
    from /home/wuguoyao/.rvm/gems/ruby-1.9.2-p0@rails3/gems/enginex-0.8.1/lib/enginex.rb:2:in`<top (required)>'
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/wuguoyao/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /home/wuguoyao/.rvm/gems/ruby-1.9.2-p0@rails3/gems/enginex-0.8.1/bin/enginex:4:in `<top (required)>'
    from /home/wuguoyao/.rvm/gems/ruby-1.9.2-p0@rails3/bin/enginex:19:in`load'
    from /home/wuguoyao/.rvm/gems/ruby-1.9.2-p0@rails3/bin/enginex:19:in `<main>'

**Comment by josevalim** [comment]
This is a rubygems bug. I haven't got the chance to fix it yet. You need to uninstall your older versions of activesupport and rails and just have the more recent one.

**Comment by ghost** [comment]
Thanks a lot.
